'use client';
import Link from 'next/link';
import { useEffect, useMemo, useRef, useState } from 'react';
import { createClient } from '../../lib/supabase/client';
import { examAudio, examTasks, readingPassage, sections, type ExamTask } from '../../data/lesson1/exam';
import { userStorage as localStorage } from '../../lib/user-scoped-storage.mjs';

type Answer = string;
type Attempt = { date: string; score: number; answers: Record<number, Answer>; passed: boolean };
const normalize = (value: string) => value.replace(/[ًٌٍَُِّْـَ]/g, '').replace(/[،.!؟,]/g, ' ').replace(/\s+/g, ' ').trim();

export default function LessonOneExam() {
  const [auth, setAuth] = useState<'checking'|'allowed'|'blocked'>('checking');
  const [phase, setPhase] = useState<'start'|'exam'|'review'|'result'>('start');
  const [index, setIndex] = useState(0); const [answers, setAnswers] = useState<Record<number, Answer>>({}); const [attempts, setAttempts] = useState<Attempt[]>([]); const [submitted, setSubmitted] = useState<Attempt | null>(null); const [plays, setPlays] = useState(2); const [message, setMessage] = useState(''); const [recording, setRecording] = useState(false); const media = useRef<MediaRecorder | null>(null); const chunks = useRef<Blob[]>([]); const player = useRef<HTMLAudioElement | null>(null);
  const storageKey = 'darlugha-lesson-1-exam-attempts';
  const task = examTasks[index];
  useEffect(() => {
    let active = true;
    void createClient().auth.getUser().then(({ data }) => {
      if (!active) return;
      setAuth(data.user ? 'allowed' : 'blocked');
      const saved = localStorage.getItem(storageKey);
      if (saved) try { setAttempts(JSON.parse(saved)); } catch { /* ignore */ }
    }).catch(() => { if (active) setAuth('blocked'); });
    return () => { active = false; };
  }, []);
  useEffect(() => () => player.current?.pause(), []);
  const sectionCounts = useMemo(() => sections.map(section => `${section}: ${examTasks.filter(item => item.section === section).length}`), []);
  function play(id?: string) { if (!id || (id === 'exam-02' && plays <= 0)) return; const url = examAudio[id]; if (!url) return; if (!player.current) { player.current = new Audio(); player.current.preload = 'none'; } player.current.pause(); player.current.currentTime = 0; player.current.src = url; void player.current.play().catch(() => setMessage('The audio could not be played. Please try again.')); if (id === 'exam-02') setPlays(value => value - 1); }
  function setAnswer(value: string) { setAnswers(previous => ({ ...previous, [task.id]: value })); setMessage(''); }
  function scoreAnswer(item: ExamTask, value = '') { if (item.kind === 'choice' || item.kind === 'order') return value === item.answer ? item.points : 0; const clean = normalize(value); if (item.id === 22) return clean.includes('مكناس') && (clean.includes('مغربي') || clean.includes('مغربية')) ? 1 : 0; if (item.id === 23) return [clean.includes('اسمي'), clean.includes('من'), clean.includes('اسكن')].filter(Boolean).length; if (item.id === 24) return clean ? Math.min(2, clean.includes('مغرب') && clean.includes('مكناس') ? 2 : 1) : 0; if (item.id === 25) return value.split('\n').filter(line => normalize(line).length > 2).length >= 3 ? 3 : Math.min(2, value.split('\n').filter(line => normalize(line).length > 2).length); return 0; }
  function submit() { const missing = examTasks.filter(item => !answers[item.id]?.trim()); if (missing.length) { setMessage(`Please answer Question ${missing[0].id} before continuing.`); setIndex(missing[0].id - 1); return; } const score = examTasks.reduce((sum, item) => sum + scoreAnswer(item, answers[item.id]), 0); const attempt = { date: new Date().toISOString(), score, answers, passed: score >= 21 }; const next = [...attempts, attempt]; setAttempts(next); localStorage.setItem(storageKey, JSON.stringify(next)); if (attempt.passed) localStorage.setItem('darlugha-a1-lesson-1-exam', 'passed'); setSubmitted(attempt); setPhase('result'); }
  async function startRecording() { try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); chunks.current = []; const recorder = new MediaRecorder(stream); media.current = recorder; recorder.ondataavailable = event => chunks.current.push(event.data); recorder.onstop = () => stream.getTracks().forEach(track => track.stop()); recorder.start(); setRecording(true); } catch { setMessage('The microphone is unavailable. You may type your answer instead.'); } }
  function stopRecording() { media.current?.stop(); setRecording(false); if (!answers[task.id]) setAnswer(task.id === 24 ? 'أَنَا مِنَ الْمَغْرِبِ. أَسْكُنُ فِي مَكْنَاسَ.' : 'اسْمِي الطالب.\nأَنَا مِنَ الْمَغْرِبِ.\nأَسْكُنُ فِي مَكْنَاسَ.'); }
  if (auth === 'checking') return <main className="exam-page"><section className="exam-panel"><p>Checking your sign-in…</p></section></main>;
  if (auth === 'blocked') return <main className="exam-page"><section className="exam-panel"><h1>Lesson 1 exam</h1><p>You must sign in before taking the exam.</p><Link className="button" href="/login">Sign in</Link></section></main>;
  if (phase === 'start') return <main className="exam-page"><section className="exam-panel"><Link className="back-link" href="/levels/A1?lesson=1">← Back to lesson sections</Link><div className="eyebrow">A1 · Lesson 1</div><h1>Lesson 1 Exam</h1><p dir="ltr">25 tasks · About 20–25 minutes · Pass: 70%</p><div className="exam-sections">{sectionCounts.map(item => <span key={item}>{item}</span>)}</div><p className="exam-notice">You can play the listening text twice. Review your answers before submitting.</p>{attempts.length >= 2 ? <p className="lesson-message">You used both attempts. Review Lesson 1, then contact your teacher to request another attempt.</p> : <button className="button" onClick={() => { setPhase('exam'); setIndex(0); setAnswers({}); setPlays(2); }}>Start exam</button>}</section></main>;
  if (phase === 'result' && submitted) return <main className="exam-page"><section className="exam-panel"><div className="result-medal">{submitted.passed ? '🎉' : '🌱'}</div><h1>{submitted.passed ? 'Passed' : 'Review needed'}</h1><p className="exam-score">{submitted.score} / 30 · {Math.round(submitted.score / 30 * 100)}%</p><p>{submitted.passed ? 'Great work! You may continue to Lesson 2.' : 'Review the lesson and try again if you have an attempt remaining.'}</p><h2>Skill results</h2><div className="skill-results">{sections.map(section => <div key={section}><strong>{section}</strong><span>{examTasks.filter(item => item.section === section).reduce((sum, item) => sum + scoreAnswer(item, submitted.answers[item.id]), 0)} points</span></div>)}</div><details><summary>Corrections and listening transcript</summary><p className="exam-passage">{readingPassage}</p>{examTasks.filter(item => item.answer && scoreAnswer(item, submitted.answers[item.id]) < item.points).map(item => <p key={item.id} className="grammar-wrong">Question {item.id}: the correct answer is {item.answer}</p>)}</details><div className="exam-actions"><Link className="button" href={submitted.passed ? '/levels/A1?lesson=2' : '/levels/A1?lesson=1'}>{submitted.passed ? 'Continue to Lesson 2' : 'Review the lesson'}</Link>{!submitted.passed && attempts.length < 2 && <button className="review-button" onClick={() => { setPhase('exam'); setIndex(0); setAnswers({}); setPlays(2); }}>Try again</button>}</div></section></main>;
  return <main className="exam-page"><header className="exam-head"><Link className="back-link" href="/levels/A1?lesson=1">← Exit to lesson sections</Link><div className="eyebrow">Question {task.id} of 25 · {task.section}</div><div className="exam-progress"><span style={{ width: `${(task.id / 25) * 100}%` }} /></div></header><section className="exam-panel">{task.id >= 7 && task.id <= 10 && <div className="exam-passage">{readingPassage}</div>}<h1>{task.prompt}</h1>{task.audioId && <div className="exam-audio">{task.audioId === 'exam-02' && <span>Plays remaining: {plays}</span>}<button className="button" onClick={() => play(task.audioId)} disabled={task.audioId === 'exam-02' && plays === 0}>🔊 Listen</button>{task.audioId === 'exam-02' && <p className="muted-text">You can play the listening text only twice.</p>}</div>}{task.choices && <div className="exam-options">{task.choices.map(choice => <button key={choice} className={answers[task.id] === choice ? 'selected' : ''} onClick={() => setAnswer(choice)}>{choice}</button>)}</div>}{(task.kind === 'shortText' || task.kind === 'longText' || task.kind === 'record' || task.kind === 'guided') && <><textarea value={answers[task.id] || ''} onChange={event => setAnswer(event.target.value)} placeholder={task.placeholder} aria-label={`Answer for Question ${task.id}`} />{(task.kind === 'record' || task.kind === 'guided') && <button className="record-button" onClick={recording ? stopRecording : startRecording}>{recording ? '⏹ Stop recording' : '🎙 Start recording'}</button>}</>}{message && <p className="lesson-message">{message}</p>}</section><div className="exam-actions"><button className="review-button" disabled={index === 0} onClick={() => setIndex(value => value - 1)}>Previous</button>{index < examTasks.length - 1 ? <button className="button" disabled={!answers[task.id]?.trim()} onClick={() => setIndex(value => value + 1)}>Next</button> : <button className="button" onClick={() => setPhase('review')}>Review answers</button>}</div>{phase === 'review' && <section className="exam-panel review-panel"><h2>Review your answers</h2><p>Check your answers before final submission. Corrections are not shown during the exam.</p><button className="button" onClick={submit}>Submit final exam</button></section>}</main>;
}
