'use client';

import { useEffect, useMemo, useState } from 'react';
import { lessonOneVocabulary } from '../../data/lesson1/vocabulary';
import { listeningQuestions, matchingGroups, meaningQuestions, sentenceQuestions } from '../../data/lesson1/practice';
import { playArabic } from '../../lib/audio';
import LessonCompletion from '../learning/LessonCompletion';
import { markSectionStarted } from '../../lib/learning-progress';
import { userStorage as localStorage } from '../../lib/user-scoped-storage.mjs';

type Stage = 0 | 1 | 2 | 3;
type ChoiceAttempt = 1 | 2;
type WordStats = { seen: number; correct: number; wrong: number; firstTryCorrect: number; lastReviewed: string; status: 'new' | 'learning' | 'mastered'; review: boolean };
const stageTitles = ['Choose the correct meaning', 'Match each word with its meaning', 'Listen and choose the word', 'Choose the correct word'];
const stageEnglish = ['Select the English meaning.', 'Connect every Arabic word to its English meaning.', 'Listen carefully, then select the Arabic word.', 'Complete the Arabic sentence.'];
const emptyStats = (): Record<number, WordStats> => ({});

function shuffle<T>(items: readonly T[]) { return [...items].sort(() => Math.random() - 0.5); }
function speak(text: string, rate = 0.82) {
  const normalized = text.normalize('NFD').replace(/[\u064B-\u065F\u0670\s]/g, '').replace(/[؟،.]/g, '');
  // The supplied recording mapped عُمْرٌ to عُنْوَانٌ. Keep it silent until the correct asset is supplied.
  if (normalized === 'عمر') return false;
  const meaning = meaningQuestions.find(item => item.word === text);
  const listening = listeningQuestions.find(item => item.word === text);
  const sentence = sentenceQuestions.find(item => item.sentence === text);
  const matching = matchingGroups.flatMap(group => group.pairs.map(pair => ({ ...pair, audioUrl: `/audio/lesson1/practice/matching/${group.id}-${String(pair.wordId).padStart(2, '0')}.mp3` }))).find(item => item.word === text);
  const conjugation = ['أَنَا أَعْمَلُ', 'أَنْتَ تَعْمَلُ', 'أَنْتِ تَعْمَلِينَ', 'هُوَ يَعْمَلُ', 'هِيَ تَعْمَلُ'].indexOf(text);
  const audioUrl = sentence?.audioUrl || listening?.audioUrl || matching?.audioUrl || (meaning ? `/audio/lesson1/practice/meaning/meaning-${String(meaning.wordId).padStart(2, '0')}.mp3` : conjugation >= 0 ? `/audio/lesson1/practice/conjugation/conjugation-${String(conjugation + 1).padStart(2, '0')}.mp3` : undefined);
  return playArabic(text, audioUrl, rate);
}
function readSavedStats() { try { return JSON.parse(localStorage.getItem('darlugha-lesson-1-vocabulary-progress') || '{}') as Record<number, WordStats>; } catch { return emptyStats(); } }

export default function VocabularyPractice() {
  const [started, setStarted] = useState(false); const [stage, setStage] = useState<Stage>(0); const [questionIndex, setQuestionIndex] = useState(0); const [score, setScore] = useState(0); const [, setAnswered] = useState(0); const [attempt, setAttempt] = useState<ChoiceAttempt>(1); const [selected, setSelected] = useState(''); const [feedback, setFeedback] = useState(''); const [stats, setStats] = useState<Record<number, WordStats>>({}); const [wrongIds, setWrongIds] = useState<number[]>([]); const [finished, setFinished] = useState(false); const [, setStartedAt] = useState(0); const [savedNotice, setSavedNotice] = useState('');
  const [meaningOrder, setMeaningOrder] = useState(meaningQuestions); const [listeningOrder, setListeningOrder] = useState(listeningQuestions); const [sentenceOrder, setSentenceOrder] = useState(sentenceQuestions.filter((question) => question.id !== 'sentence-8')); const [matchingGroup, setMatchingGroup] = useState(matchingGroups[0]); const [selectedWord, setSelectedWord] = useState(''); const [selectedMeaning, setSelectedMeaning] = useState(''); const [matched, setMatched] = useState<string[]>([]); const [matchError, setMatchError] = useState('');
  const maximumScore = 38;
  useEffect(() => { markSectionStarted('A1', 1, 'vocabulary'); }, []);

  function startPractice() { setStats(readSavedStats()); setMeaningOrder(shuffle(meaningQuestions)); setListeningOrder(shuffle(listeningQuestions)); setSentenceOrder(shuffle(sentenceQuestions.filter((question) => question.id !== 'sentence-8'))); setMatchingGroup(matchingGroups[Math.floor(Math.random() * matchingGroups.length)]); setStarted(true); setFinished(false); setStage(0); setQuestionIndex(0); setScore(0); setAnswered(0); setAttempt(1); setSelected(''); setFeedback(''); setWrongIds([]); setStartedAt(Date.now()); setSavedNotice(''); }
  function saveStats(next: Record<number, WordStats>) { setStats(next); localStorage.setItem('darlugha-lesson-1-vocabulary-progress', JSON.stringify(next)); }
  function record(wordId: number, correct: boolean, firstTry: boolean) { const old = stats[wordId] || { seen: 0, correct: 0, wrong: 0, firstTryCorrect: 0, lastReviewed: '', status: 'new', review: false }; const nextItem = { ...old, seen: old.seen + 1, correct: old.correct + (correct ? 1 : 0), wrong: old.wrong + (correct ? 0 : 1), firstTryCorrect: old.firstTryCorrect + (correct && firstTry ? 1 : 0), lastReviewed: new Date().toISOString(), status: (old.firstTryCorrect + (correct && firstTry ? 1 : 0) >= 2 ? 'mastered' : 'learning') as WordStats['status'] }; const next = { ...stats, [wordId]: nextItem }; saveStats(next); if (!correct) setWrongIds(items => items.includes(wordId) ? items : [...items, wordId]); }
  function answerChoice(correct: string, value: string, wordId: number, explanation: string) { if (selected && !feedback.includes('Second attempt')) return; setSelected(value); const isCorrect = value === correct; if (isCorrect) { setScore(points => points + (attempt === 1 ? 2 : 1)); record(wordId, true, attempt === 1); setFeedback(attempt === 1 ? `Correct ✓ ${explanation}` : `Correct on your second attempt ✓ ${explanation}`); } else if (attempt === 1) { record(wordId, false, false); setAttempt(2); setFeedback('Try again. Read the choices carefully, then choose another answer.'); } else { record(wordId, false, false); setFeedback(`The correct answer is: ${correct}`); } }
  function nextChoice() { if (!feedback) return; if (attempt === 2 && selected && !feedback.includes('Correct on') && !feedback.includes('The correct answer')) { setSelected(''); setFeedback('Second attempt: choose your answer.'); return; } advance(); }
  function advance() { setSelected(''); setFeedback(''); setAttempt(1); setAnswered(value => value + 1); if (stage === 0 && questionIndex < meaningOrder.length - 1) return setQuestionIndex(value => value + 1); if (stage === 2 && questionIndex < listeningOrder.length - 1) return setQuestionIndex(value => value + 1); if (stage === 3 && questionIndex < sentenceOrder.length - 1) return setQuestionIndex(value => value + 1); if (stage < 3) { setStage(value => (value + 1) as Stage); setQuestionIndex(0); setSelectedWord(''); setSelectedMeaning(''); setMatched([]); setMatchError(''); } else setFinished(true); }
  function exitAndSave() { setSavedNotice('Your progress has been saved. You can continue later.'); setStarted(false); localStorage.setItem('darlugha-lesson-1-vocabulary-last-exit', new Date().toISOString()); }
  function goBack() { if (stage === 0) return; setStage(value => (value - 1) as Stage); setQuestionIndex(0); setSelected(''); setFeedback(''); setAttempt(1); setMatched([]); setSelectedWord(''); setSelectedMeaning(''); }
  function chooseMatchWord(word: string) { if (matched.includes(word)) return; setSelectedWord(word); if (selectedMeaning) checkMatch(word, selectedMeaning); }
  function chooseMatchMeaning(meaning: string) { if (matched.includes(meaning)) return; setSelectedMeaning(meaning); if (selectedWord) checkMatch(selectedWord, meaning); }
  function checkMatch(word: string, meaning: string) { const pair = matchingGroup.pairs.find(item => item.word === word); if (pair?.meaning === meaning) { const next = [...matched, word, meaning]; setMatched(next); setSelectedWord(''); setSelectedMeaning(''); setMatchError('Correct match ✓'); if (next.length === matchingGroup.pairs.length * 2) setFeedback('All pairs are matched.'); } else { setMatchError('That pair does not match. Try again.'); setSelectedWord(''); setSelectedMeaning(''); } }
  function finishMatch() { if (matched.length < matchingGroup.pairs.length * 2) return; matchingGroup.pairs.forEach(pair => record(pair.wordId, true, true)); setScore(value => value + matchingGroup.pairs.length * 2); advance(); }
  function percent() { return Math.round((score / maximumScore) * 100); }
  if (!started) return <section className="practice-intro" dir="ltr"><div className="eyebrow">Interactive practice · 7–10 minutes</div><h2>Practice the vocabulary</h2><p>Recall, understand, and use the new words in four short stages.</p><div className="practice-benefits"><span>✓ 19 questions per attempt</span><span>✓ Arabic audio on demand</span><span>✓ Progress saved for each word</span></div>{savedNotice && <p className="practice-saved">{savedNotice}</p>}<button className="practice-start" type="button" onClick={startPractice}>Start practice →</button></section>;
  if (finished) return <PracticeResults score={score} percent={percent()} wrongIds={wrongIds} stats={stats} onRetry={startPractice} />;
  return <section className="practice-shell" aria-label="Vocabulary practice"><div className="practice-header"><div><div className="practice-stage" dir="ltr">Stage {stage + 1} of 4</div><h2 dir="ltr">{stageTitles[stage]}</h2><p dir="ltr">{stageEnglish[stage]}</p></div><div className="practice-score"><strong>{score}</strong><span>points</span></div></div><div className="practice-progress"><span style={{ width: `${((stage + 1) / 4) * 100}%` }} /></div><div className="practice-tools"><button type="button" onClick={() => speak(`المرحلة ${stage + 1}`)}>🔊 Play stage number</button><button type="button" onClick={exitAndSave}>Save and exit</button></div><div className="practice-body">{stage === 0 && <MeaningChoice question={meaningOrder[questionIndex]} selected={selected} feedback={feedback} onAnswer={answerChoice} onSpeak={speak} />}{stage === 1 && <MatchingExercise group={matchingGroup} selectedWord={selectedWord} selectedMeaning={selectedMeaning} matched={matched} message={matchError} onWord={chooseMatchWord} onMeaning={chooseMatchMeaning} onSpeak={speak} />}{stage === 2 && <ListeningChoice question={listeningOrder[questionIndex]} selected={selected} feedback={feedback} onAnswer={answerChoice} onSpeak={speak} />}{stage === 3 && <SentenceCompletion question={sentenceOrder[questionIndex]} selected={selected} feedback={feedback} onAnswer={answerChoice} onSpeak={speak} />}</div><div className="practice-navigation"><button type="button" className="practice-back" onClick={goBack} disabled={stage === 0}>← Previous stage</button>{stage === 1 ? <button type="button" className="practice-next" onClick={finishMatch} disabled={matched.length < matchingGroup.pairs.length * 2}>{feedback || 'Next →'}</button> : <button type="button" className="practice-next" onClick={nextChoice} disabled={!feedback}>{feedback ? 'Next →' : 'Choose an answer first'}</button>}</div></section>;
}

function MeaningChoice({ question, selected, feedback, onAnswer, onSpeak }: { question: typeof meaningQuestions[number]; selected: string; feedback: string; onAnswer: (correct: string, value: string, wordId: number, explanation: string) => void; onSpeak: (text: string) => boolean }) { const choices = useMemo(() => shuffle(question.choices), [question]); return <div className="exercise-card"><div className="exercise-prompt"><span className="exercise-visual">{question.visual}</span><h3>{question.word}</h3><button type="button" className="large-sound" onClick={() => onSpeak(question.word)} aria-label={`Play ${question.word}`}>🔊</button></div><p className="exercise-hint" dir="ltr">Choose the correct English meaning.</p><div className="choice-grid">{choices.map(choice => <button key={choice} type="button" className={selected === choice ? (choice === question.correct ? 'choice correct' : 'choice wrong') : 'choice'} onClick={() => onAnswer(question.correct, choice, question.wordId, `It means “${question.correct}.”`)}>{choice}</button>)}<button type="button" className="choice dont-know" onClick={() => onAnswer(question.correct, 'I do not know', question.wordId, `It means “${question.correct}.”`)}>I do not know</button></div>{feedback && <p className="exercise-feedback">{feedback}</p>}</div>; }
function MatchingExercise({ group, selectedWord, selectedMeaning, matched, message, onWord, onMeaning, onSpeak }: { group: typeof matchingGroups[number]; selectedWord: string; selectedMeaning: string; matched: string[]; message: string; onWord: (value: string) => void; onMeaning: (value: string) => void; onSpeak: (value: string) => boolean }) { const words = useMemo(() => shuffle(group.pairs), [group]); const meanings = useMemo(() => shuffle(group.pairs.map(pair => pair.meaning)), [group]); return <div className="exercise-card"><p className="exercise-hint" dir="ltr">Select an Arabic word, then select its English meaning.</p><div className="matching-grid"><div><h3>Arabic</h3>{words.map(pair => <button type="button" key={pair.word} className={matched.includes(pair.word) ? 'match-item matched' : selectedWord === pair.word ? 'match-item selected' : 'match-item'} onClick={() => { onWord(pair.word); onSpeak(pair.word); }}>{pair.word}</button>)}</div><div><h3 dir="ltr">English</h3>{meanings.map(meaning => <button type="button" dir="ltr" key={meaning} className={matched.includes(meaning) ? 'match-item matched' : selectedMeaning === meaning ? 'match-item selected' : 'match-item'} onClick={() => onMeaning(meaning)}>{meaning}</button>)}</div></div>{message && <p className="exercise-feedback">{message}</p>}</div>; }
function ListeningChoice({ question, selected, feedback, onAnswer }: { question: typeof listeningQuestions[number]; selected: string; feedback: string; onAnswer: (correct: string, value: string, wordId: number, explanation: string) => void; onSpeak: (text: string, rate?: number) => boolean }) { const choices = useMemo(() => shuffle(question.choices), [question]); const play = () => playArabic(question.word, question.audioUrl, .8); return <div className="exercise-card listening-card"><button type="button" className="listen-main" onClick={play}>🔊<span>Listen to the word</span><small>You may listen more than once</small></button><button type="button" className="slow-button" onClick={play}>Speed 0.8×</button><p className="exercise-hint" dir="ltr">Listen, then choose the Arabic word you heard.</p><div className="choice-grid arabic-choices">{choices.map(choice => <button type="button" key={choice} className={selected === choice ? (choice === question.word ? 'choice correct' : 'choice wrong') : 'choice'} onClick={() => onAnswer(question.word, choice, question.wordId, `${question.word} means “${question.meaning}.”`)}>{choice}</button>)}</div>{feedback && <p className="exercise-feedback">{feedback}</p>}</div>; }
function SentenceCompletion({ question, selected, feedback, onAnswer, onSpeak }: { question: typeof sentenceQuestions[number]; selected: string; feedback: string; onAnswer: (correct: string, value: string, wordId: number, explanation: string) => void; onSpeak: (text: string) => boolean }) { const choices = useMemo(() => shuffle(question.choices), [question]); return <div className="exercise-card"><h3 className="sentence-text">{question.sentence}</h3><button type="button" className="sound-button" onClick={() => onSpeak(question.sentence)} aria-label="Play the sentence">🔊 Listen to the sentence</button><p className="translation" dir="ltr">{question.translation}</p><div className="choice-grid arabic-choices">{choices.map(choice => <button type="button" key={choice} className={selected === choice ? (choice === question.answer ? 'choice correct' : 'choice wrong') : 'choice'} onClick={() => onAnswer(question.answer, choice, question.wordId, `${question.answer} is the correct word here.`)}>{choice}</button>)}</div>{feedback && <p className="exercise-feedback">{feedback}</p>}</div>; }
function PracticeResults({ score, percent, wrongIds, stats, onRetry }: { score: number; percent: number; wrongIds: number[]; stats: Record<number, WordStats>; onRetry: () => void }) { const wrongWords = wrongIds.map(id => lessonOneVocabulary.find(item => item.id === id)).filter(Boolean); return <section className="practice-results">{wrongWords.length > 0 && <div className="mistakes"><h3 dir="ltr">Words to review</h3>{wrongWords.map(item => item && <div className="mistake-row" key={item.id}><b>{item.word}</b><span dir="ltr">{item.meaning}</span><button type="button" aria-label={`Play ${item.word}`} onClick={() => speak(item.word)}>🔊</button></div>)}</div>}<p dir="ltr">Mastered this attempt: <b>{Object.values(stats).filter(item => item.status === 'mastered').length}</b></p><LessonCompletion level="A1" lesson={1} section="vocabulary" passed={percent >= 70} score={`${percent}% · ${score}/38 points`} onRetry={onRetry} /></section>; }
