'use client';

/* eslint-disable @next/next/no-img-element -- Preserve the lesson bundle's responsive hero sizing. */

import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { lesson02Listening } from '../../data/lesson2/listening';
import { lesson02ListeningPractice } from '../../data/lesson2/listening-practice';
import { markLesson2SectionStarted } from '../../lib/lesson2-progress';
import { stableShuffle } from '../../lib/stable-shuffle';
import LessonCompletion from '../learning/LessonCompletion';
import { userStorage as localStorage } from '../../lib/user-scoped-storage.mjs';

type Stage = 'prediction' | 'gist' | 'details' | 'speaker' | 'order' | 'read' | 'shadow' | 'results';
const order: Stage[] = ['prediction', 'gist', 'details', 'speaker', 'order', 'read', 'shadow', 'results'];

export default function LessonTwoListening() {
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const [stage, setStage] = useState<Stage>('prediction');
  const [index, setIndex] = useState(0); const [score, setScore] = useState(0); const [answer, setAnswer] = useState(''); const [feedback, setFeedback] = useState(''); const [translation, setTranslation] = useState(false); const [playing, setPlaying] = useState(''); const [audioStatus, setAudioStatus] = useState<'idle'|'loading'|'playing'|'paused'|'error'>('idle'); const [orderAnswers, setOrderAnswers] = useState<string[]>([]); const [attempts, setAttempts] = useState(0);
  useEffect(() => {
    markLesson2SectionStarted('listening');
    const frame = window.requestAnimationFrame(() => {
      try {
        const saved = JSON.parse(localStorage.getItem('darlugha-lesson-2-listening-progress') || '{}');
        if (saved.stage) setStage(saved.stage);
        if (typeof saved.score === 'number') setScore(saved.score);
      } catch {
        // Invalid local progress should not block the activity.
      }
    });
    return () => window.cancelAnimationFrame(frame);
  }, []);
  useEffect(() => () => audioRef.current?.pause(), []);
  function play(url: string, id: string) { if (!audioRef.current) { audioRef.current = new Audio(); audioRef.current.preload = 'none'; audioRef.current.onended = () => { setPlaying(''); setAudioStatus('idle'); }; audioRef.current.onerror = () => setAudioStatus('error'); } const audio = audioRef.current; if (playing === id) { if (audio.paused) void audio.play().then(() => setAudioStatus('playing')).catch(() => setAudioStatus('error')); else { audio.pause(); setAudioStatus('paused'); } return; } audio.pause(); audio.src = url; audio.currentTime = 0; setPlaying(id); setAudioStatus('loading'); void audio.play().then(() => setAudioStatus('playing')).catch(() => setAudioStatus('error')); }
  function save(nextStage = stage, nextScore = score) { localStorage.setItem('darlugha-lesson-2-listening-progress', JSON.stringify({ stage: nextStage, score: nextScore, translation, attempts })); }
  function clearQuestion() { setAnswer(''); setFeedback(''); setOrderAnswers([]); }
  function choose(value: string, correct: string, explanation: string, count = true, replay?: string) { if (feedback) return; setAnswer(value); const ok = value === correct; const nextScore = ok && count ? score + 1 : score; if (ok && count) setScore(nextScore); setAttempts(n => n + 1); setFeedback(ok ? `Correct ✓ ${explanation}` : `Try again. The correct answer is: ${correct}. ${explanation}`); save(stage, nextScore); if (replay) play(`${lesson02ListeningManifestBase}/${replay.replace(/^audio\//, '')}`, `replay-${replay}`); }
  function go(nextStage: Stage) { clearQuestion(); setIndex(0); setStage(nextStage); save(nextStage); }
  function next() { if (stage === 'prediction' && index < lesson02ListeningPractice.prediction.length - 1) { setIndex(n => n + 1); clearQuestion(); return; } if (stage === 'prediction') return go('gist'); if (stage === 'gist') return go('details'); if (stage === 'details' && index < lesson02ListeningPractice.details.length - 1) { setIndex(n => n + 1); clearQuestion(); return; } if (stage === 'details') return go('speaker'); if (stage === 'speaker' && index < lesson02ListeningPractice.speakerIdentification.length - 1) { setIndex(n => n + 1); clearQuestion(); return; } if (stage === 'speaker') return go('order'); if (stage === 'order') return go('read'); if (stage === 'read') return go('shadow'); if (stage === 'shadow') { localStorage.setItem('darlugha-lesson-2-listening-complete', 'true'); return setStage('results'); } }
  function reset() { audioRef.current?.pause(); setStage('prediction'); setIndex(0); setScore(0); setAnswer(''); setFeedback(''); setOrderAnswers([]); setPlaying(''); setAudioStatus('idle'); }
  const lesson02ListeningManifestBase = '/audio/lesson-02/listening';
  const prediction = lesson02ListeningPractice.prediction[index]; const detail = lesson02ListeningPractice.details[index]; const speaker = lesson02ListeningPractice.speakerIdentification[index]; const speakerLine = lesson02Listening.dialogue.find(line => line.id === speaker?.lineId); const total = 1 + lesson02ListeningPractice.details.length + lesson02ListeningPractice.speakerIdentification.length + 1; const percent = Math.round(score / total * 100); const progress = Math.round(order.indexOf(stage) / (order.length - 1) * 100);
  return <section className="listening-lesson" aria-label="Lesson 2 listening"><div className="listening-hero"><img src="/images/lesson-02/listening-prediction-translation-center.png" alt="A Moroccan translation center" /><div className="listening-hero-copy"><Link className="back-link" href="/levels/A1?lesson=2">← Lesson sections</Link><div className="eyebrow">A1 · Lesson 2</div><h1>{stage === 'prediction' ? 'Look and predict' : lesson02Listening.title.ar}</h1><p dir="ltr">{lesson02Listening.title.en}</p><div className="reading-progress"><strong>{progress}%</strong><span>Listening progress</span></div></div></div>
    {stage === 'prediction' && <Question seed={prediction.id} title="انظر وتوقّع" prompt={prediction.promptAr} options={prediction.options} answer={answer} feedback={feedback} onAnswer={value => choose(value, prediction.options[prediction.answer], 'هذا توقّع فقط ولا يدخل في الدرجة.', false)} onNext={next} />}
    {stage === 'gist' && <AudioQuestion seed={lesson02ListeningPractice.gist.id} title="الاستماع الأول" prompt={lesson02ListeningPractice.gist.promptAr} options={lesson02ListeningPractice.gist.options} answer={answer} feedback={feedback} onPlay={() => play(`${lesson02ListeningManifestBase}/dialogue-full.mp3`, 'full')} audioStatus={audioStatus} onAnswer={value => choose(value, lesson02ListeningPractice.gist.options[lesson02ListeningPractice.gist.answer], lesson02ListeningPractice.gist.feedbackEn)} onNext={next} />}
    {stage === 'details' && <AudioQuestion seed={detail.id} title="الاستماع الثاني · فهم التفاصيل" prompt={detail.promptAr} options={detail.options} answer={answer} feedback={feedback} onPlay={() => play(`${lesson02ListeningManifestBase}/${detail.replay.replace(/^audio\//, '')}`, detail.id)} audioStatus={audioStatus} onAnswer={value => choose(value, detail.options[detail.answer], detail.feedbackEn, true, detail.replay)} onNext={next} />}
    {stage === 'speaker' && <AudioQuestion seed={speaker.lineId} title="من قال ذلك؟" prompt={`${speakerLine?.ar || ''} — مَنْ قَالَ هٰذِهِ الجُمْلَةَ؟`} options={['عُمَر', 'هُدَى']} answer={answer} feedback={feedback} onPlay={() => speakerLine && play(`${lesson02ListeningManifestBase}/${speakerLine.audio.replace(/^audio\//, '')}`, speaker.lineId)} audioStatus={audioStatus} onAnswer={value => choose(value, speaker.answer === 'omar' ? 'عُمَر' : 'هُدَى', speakerLine?.en || '', true, speakerLine?.audio)} onNext={next} />}
    {stage === 'order' && <div className="listening-panel listening-question"><div className="eyebrow">ORDER WHAT YOU HEARD</div><h2>Select the events in the order you heard them.</h2><div className="listening-options">{stableShuffle(lesson02ListeningPractice.eventOrder, 'lesson-02-listening-event-order').map(item => <button type="button" className={orderAnswers.includes(item) ? 'selected' : ''} disabled={orderAnswers.includes(item)} key={item} onClick={() => { const nextOrder = [...orderAnswers, item]; setOrderAnswers(nextOrder); if (nextOrder.length === lesson02ListeningPractice.eventOrder.length) { const correct = nextOrder.every((value, itemIndex) => value === lesson02ListeningPractice.eventOrder[itemIndex]); if (correct) setScore(n => n + 1); setFeedback(correct ? 'Correct ✓ The order is right.' : `Try again. The correct order starts with: ${lesson02ListeningPractice.eventOrder[0]}`); } }}>{item}</button>)}</div>{orderAnswers.length > 0 && !feedback && <p className="listening-note">Selected: {orderAnswers.join(' ← ')}</p>}{feedback && <p className="reading-feedback">{feedback}</p>}<button className="review-button" type="button" disabled={Boolean(feedback) || orderAnswers.length === 0} onClick={() => setOrderAnswers([])}>Reset order</button><button className="button" type="button" disabled={!feedback} onClick={next}>Continue →</button></div>}
    {stage === 'read' && <div className="listening-panel audio-stage"><div className="eyebrow">LISTEN AND READ</div><div className="audio-controls"><button className="reading-audio-button" type="button" onClick={() => play(`${lesson02ListeningManifestBase}/dialogue-learning-pauses.mp3`, 'learning')} aria-label="Play the practice dialogue">🔊 {playing === 'learning' && audioStatus === 'playing' ? 'Pause' : 'Play dialogue'}</button><button className="review-button" type="button" onClick={() => setTranslation(value => !value)}>{translation ? 'Hide English' : 'Show English'}</button></div><div className="dialogue-lines">{lesson02Listening.dialogue.map(line => <div className={`dialogue-line ${line.speaker === 'huda' ? 'salma' : 'yassine'}`} key={line.id}><strong>{line.speaker === 'huda' ? 'هُدَى' : 'عُمَر'}</strong><span>{line.ar}</span><button className="review-button" type="button" onClick={() => play(`${lesson02ListeningManifestBase}/${line.audio.replace(/^audio\//, '')}`, line.id)} aria-label={`Play dialogue line ${line.order}`}>🔊</button>{translation && <small dir="ltr">{line.en}</small>}</div>)}</div><button className="button" type="button" onClick={next}>I finished reading →</button></div>}
    {stage === 'shadow' && <div className="listening-panel audio-stage"><div className="eyebrow">LISTEN AND REPEAT</div><h2>Listen to each sentence, then repeat it.</h2>{lesson02ListeningPractice.shadowing.map(item => <div className="dialogue-line" key={item.id}><span>{item.text}</span><button className="review-button" type="button" onClick={() => play(`${lesson02ListeningManifestBase}/${item.audio.replace(/^audio\//, '')}`, item.id)} aria-label="Play the repetition sentence">🔊</button></div>)}<p className="listening-note" dir="ltr">Recording is optional. You can repeat without using the microphone.</p><button className="button" type="button" onClick={next}>Finish listening →</button></div>}
    {stage === 'results' && <LessonCompletion level="A1" lesson={2} section="listening" passed={percent >= 70} score={`${percent}% · ${score}/${total} correct`} onRetry={reset} />}
  </section>;
}

function Question({ seed, title, prompt, options, answer, feedback, onAnswer, onNext }: { seed: string; title: string; prompt: string; options: readonly string[]; answer: string; feedback: string; onAnswer: (value: string) => void; onNext: () => void }) { return <div className="listening-panel listening-question"><div className="eyebrow">{title}</div><h2>{prompt}</h2><div className="listening-options">{stableShuffle(options, seed).map(option => <button type="button" className={answer === option ? 'selected' : ''} key={option} onClick={() => onAnswer(option)}>{option}</button>)}</div>{feedback && <p className="reading-feedback">{feedback}</p>}<button className="button" type="button" disabled={!feedback} onClick={onNext}>Next →</button></div>; }

function AudioQuestion({ seed, title, prompt, options, answer, feedback, onAnswer, onNext, onPlay, audioStatus }: { seed: string; title: string; prompt: string; options: readonly string[]; answer: string; feedback: string; onAnswer: (value: string) => void; onNext: () => void; onPlay: () => void; audioStatus: string }) { return <div className="listening-panel listening-question"><div className="eyebrow">{title}</div><button className="reading-audio-button" type="button" onClick={onPlay} aria-label="Play the recording">🔊 Listen {audioStatus === 'loading' ? '…' : ''}</button><h2>{prompt}</h2><div className="listening-options">{stableShuffle(options, seed).map(option => <button type="button" className={answer === option ? 'selected' : ''} key={option} onClick={() => onAnswer(option)}>{option}</button>)}</div>{feedback && <p className="reading-feedback">{feedback}</p>}<button className="button" type="button" disabled={!feedback} onClick={onNext}>Next →</button></div>; }
