'use client';

/* eslint-disable @next/next/no-img-element -- Preserve the lesson bundle's responsive image sizing. */

import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { lesson02Conversation } from '../../data/lesson2/conversation';
import { lesson02ConversationPractice } from '../../data/lesson2/conversation-practice';
import manifest from '../../data/lesson2/conversation-manifest.json';
import { markLesson2SectionComplete, markLesson2SectionStarted } from '../../lib/lesson2-progress';
import LessonCompletion from '../learning/LessonCompletion';
import { userStorage as localStorage } from '../../lib/user-scoped-storage.mjs';

const base = '/audio/lesson-02/conversation';
const clips = Object.fromEntries(manifest.clips.map((clip) => [clip.id, clip.file])) as Record<string, string>;
type Stage = 'prediction' | 'watch' | 'comprehension' | 'build' | 'substitute' | 'pronunciation' | 'roleplay' | 'ai' | 'report';
const stages: Stage[] = ['prediction', 'watch', 'comprehension', 'build', 'substitute', 'pronunciation', 'roleplay', 'ai', 'report'];

export default function LessonTwoConversation() {
  const audio = useRef<HTMLAudioElement | null>(null);
  const [stage, setStage] = useState<Stage>('prediction'); const [index, setIndex] = useState(0); const [answer, setAnswer] = useState(''); const [feedback, setFeedback] = useState(''); const [score, setScore] = useState(0); const [comprehensionCorrect, setComprehensionCorrect] = useState(0); const [translation, setTranslation] = useState(false); const [playing, setPlaying] = useState(''); const [audioState, setAudioState] = useState('idle'); const [built, setBuilt] = useState(0); const [role, setRole] = useState('student'); const [turn, setTurn] = useState(0); const [message, setMessage] = useState(''); const [reportViewed, setReportViewed] = useState(false); const [attempts, setAttempts] = useState(0);
  useEffect(() => {
    markLesson2SectionStarted('conversation');
    const frame = window.requestAnimationFrame(() => {
      try {
        const saved = JSON.parse(localStorage.getItem('darlugha-lesson-2-conversation-progress') || '{}');
        if (saved.stage) setStage(saved.stage);
        if (typeof saved.score === 'number') setScore(saved.score);
        if (typeof saved.comprehensionCorrect === 'number') setComprehensionCorrect(saved.comprehensionCorrect);
        if (typeof saved.built === 'number') setBuilt(saved.built);
        if (typeof saved.turn === 'number') setTurn(saved.turn);
        if (typeof saved.reportViewed === 'boolean') setReportViewed(saved.reportViewed);
      } catch {
        // Invalid local progress should not block the activity.
      }
    });
    return () => window.cancelAnimationFrame(frame);
  }, []);
  useEffect(() => () => audio.current?.pause(), []);
  function play(id: string) { const file = clips[id]; if (!file) return; if (!audio.current) { audio.current = new Audio(); audio.current.preload = 'none'; audio.current.onended = () => { setPlaying(''); setAudioState('idle'); }; audio.current.onerror = () => setAudioState('error'); } const player = audio.current; if (playing === id) { if (player.paused) void player.play().then(() => setAudioState('playing')).catch(() => setAudioState('error')); else { player.pause(); setAudioState('paused'); } return; } player.pause(); player.src = `${base}/${file}`; player.currentTime = 0; setPlaying(id); setAudioState('loading'); void player.play().then(() => setAudioState('playing')).catch(() => setAudioState('error')); }
  function save(nextStage = stage, nextScore = score) { localStorage.setItem('darlugha-lesson-2-conversation-progress', JSON.stringify({ stage: nextStage, score: nextScore, comprehensionCorrect, built, turn, attempts, reportViewed })); }
  function clear() { setAnswer(''); setFeedback(''); }
  function go(next: Stage) { clear(); setIndex(0); setStage(next); save(next); }
  function answerQuestion(value: string, correct: string, explanation: string, graded = true, category?: 'comprehension' | 'build') { if (feedback) return; setAnswer(value); const ok = value === correct; const nextScore = ok && graded ? score + 1 : score; if (ok && graded) setScore(nextScore); if (ok && category === 'comprehension') setComprehensionCorrect(n => n + 1); setAttempts(n => n + 1); setFeedback(ok ? `Correct ✓ ${explanation}` : `Try again. The correct answer is: ${correct}. ${explanation}`); save(stage, nextScore); }
  function next() { if (stage === 'prediction' && index < lesson02Conversation.prediction.questions.length - 1) { setIndex(n => n + 1); clear(); return; } if (stage === 'prediction') return go('watch'); if (stage === 'watch') return go('comprehension'); if (stage === 'comprehension' && index < lesson02ConversationPractice.comprehension.length - 1) { setIndex(n => n + 1); clear(); return; } if (stage === 'comprehension') return go('build'); if (stage === 'build' && index < lesson02ConversationPractice.buildDialogue.length - 1) { setIndex(n => n + 1); clear(); return; } if (stage === 'build') return go('substitute'); if (stage === 'substitute') return go('pronunciation'); if (stage === 'pronunciation') return go('roleplay'); if (stage === 'roleplay') return go('ai'); if (stage === 'ai' && turn < 5) { setTurn(n => n + 1); setMessage(''); return; } if (stage === 'ai') return go('report'); }
  function reset() { audio.current?.pause(); setStage('prediction'); setIndex(0); setScore(0); setComprehensionCorrect(0); setTurn(0); setBuilt(0); setMessage(''); setReportViewed(false); clear(); setPlaying(''); setAudioState('idle'); }
  const prediction = lesson02Conversation.prediction.questions[index]; const comprehension = lesson02ConversationPractice.comprehension[index]; const build = lesson02ConversationPractice.buildDialogue[index]; const percent = Math.round(score / (lesson02ConversationPractice.comprehension.length + lesson02ConversationPractice.buildDialogue.length) * 100); const progress = Math.round(stages.indexOf(stage) / (stages.length - 1) * 100); const completionCriteriaMet = comprehensionCorrect >= lesson02ConversationPractice.completion.minimumComprehensionCorrect && built === lesson02ConversationPractice.buildDialogue.length && turn >= 5;
  return <main className="shell speaking-page" dir="rtl"><header className="speaking-head"><Link className="back-link" href="/levels/A1?lesson=2">← Lesson sections</Link><div className="eyebrow">A1 · Lesson 2</div><h1>{stage === 'prediction' ? 'Conversation at Dar Lugha Center' : lesson02Conversation.title.ar}</h1><p dir="ltr">{lesson02Conversation.title.en}</p><div className="speaking-progress"><span style={{ width: `${progress}%` }} /></div></header>
    {stage === 'prediction' && <section className="speaking-panel"><img className="conversation-cover" src="/images/lesson-02/lesson-02-conversation-cover.png" alt="New students at Dar Lugha Center" /><div className="eyebrow">LOOK AND PREDICT</div><h2>{prediction.prompt.ar}</h2><div className="reading-options">{prediction.options.map((option: string) => <button type="button" className={answer === option ? 'selected' : ''} key={option} onClick={() => answerQuestion(option, prediction.options[prediction.correctIndex], 'This prediction question does not affect your score.', false)}>{option}</button>)}</div>{feedback && <p className="reading-feedback">{feedback}</p>}<button className="button" disabled={!feedback} onClick={next}>Watch and listen →</button></section>}
    {stage === 'watch' && <section className="speaking-panel"><h2>Watch and listen</h2><button className="button" type="button" onClick={() => play(lesson02Conversation.fullDialogueAudioId)}>🔊 Listen to the full dialogue</button><p dir="ltr">{audioState === 'error' ? 'The audio could not be loaded. Please try again.' : 'Audio never starts automatically.'}</p><div className="dialogue-lines">{lesson02Conversation.dialogue.map((entry) => <div className={`dialogue-line ${entry.speaker}`} key={entry.id}><strong>{entry.speakerAr}</strong><span>{entry.text}</span>{translation && <small dir="ltr">{entry.translation}</small>}<button className="review-button" type="button" onClick={() => play(entry.audioId)} aria-label={`Play dialogue line ${entry.id}`}>🔊</button></div>)}</div><button className="review-button" type="button" onClick={() => setTranslation(v => !v)}>{translation ? 'Hide translation' : 'Show English translation'}</button><button className="button" type="button" onClick={next}>Understand the dialogue →</button></section>}
    {stage === 'comprehension' && <Question title="UNDERSTAND THE DIALOGUE" prompt={comprehension.prompt} options={comprehension.options} answer={answer} feedback={feedback} onAnswer={value => answerQuestion(value, comprehension.options[comprehension.correctIndex], comprehension.feedbackEn, true, 'comprehension')} onReplay={() => play(comprehension.evidenceAudioId)} onNext={next} />}
    {stage === 'build' && <Question title="BUILD THE DIALOGUE" prompt={build.prompt} options={build.options} answer={answer} feedback={feedback} onAnswer={value => { answerQuestion(value, build.options[build.correctIndex], build.feedbackEn, true, 'build'); if (value === build.options[build.correctIndex]) setBuilt(n => n + 1); }} onNext={() => feedback.startsWith('Correct') ? next() : clear()} nextLabel={feedback.startsWith('Correct') ? 'Next →' : 'Try Again'} />}
    {stage === 'substitute' && <section className="speaking-panel"><h2>Substitute and speak</h2>{lesson02Conversation.substitutionPatterns.map((pattern) => <article className="pronunciation-card" key={pattern.id}><h3>{pattern.template}</h3><div className="reading-options">{pattern.choices.map((choice) => <button type="button" key={choice.id} onClick={() => play(choice.audioId)}>{choice.text} 🔊</button>)}</div></article>)}<button className="button" type="button" onClick={next}>Listen and repeat →</button></section>}
    {stage === 'pronunciation' && <section className="speaking-panel"><h2>Listen and repeat</h2>{lesson02Conversation.pronunciation.map((item) => <div className="pronunciation-card" key={item.id}><strong>{item.text}</strong><button className="review-button" type="button" onClick={() => play(item.audioId)}>🔊 Listen</button></div>)}<p dir="ltr">Recording is optional. You may repeat without granting microphone permission.</p><button className="button" type="button" onClick={next}>Role play →</button></section>}
    {stage === 'roleplay' && <section className="speaking-panel"><h2>Role play</h2><div className="hint-row"><button type="button" onClick={() => setRole('student')}>I am the student</button><button type="button" onClick={() => setRole('employee')}>I am the employee</button></div><p className="ai-bubble">{role === 'student' ? 'قُلْ: نَحْنُ طُلَّابٌ جُدُدٌ. واسأل عن وقت الدرس.' : 'رَحِّبْ بِالطُّلَّابِ واسألهم عن اللغات.'}</p><textarea value={message} onChange={e => setMessage(e.target.value)} placeholder="Write your Arabic response or say it aloud…" /><button className="button" type="button" disabled={!message.trim()} onClick={next}>Finish role play →</button></section>}
    {stage === 'ai' && <section className="speaking-panel"><h2>Guided AI conversation</h2><p dir="ltr">Complete six short rounds in Modern Standard Arabic.</p><div className="ai-bubble">{['مَسَاءُ الْخَيْرِ. مَا اسْمُكَ؟','هَلْ أَنْتَ طَالِبٌ جَدِيدٌ؟','مَا اللُّغَاتُ الَّتِي تَتَكَلَّمُهَا؟','هَلْ تَدْرُسُ الْعَرَبِيَّةَ؟','مَتَى الدَّرْسُ الْيَوْمَ؟','هَلْ عِنْدَكَ دَرْسٌ غَدًا؟'][turn]}</div><input className="speaking-input" value={message} onChange={e => setMessage(e.target.value)} placeholder="Write your answer in Arabic" /><div className="hint-row"><button type="button" onClick={() => setMessage('نَعَمْ، أَنَا طَالِبٌ جَدِيدٌ.')}>Hint</button><button type="button" onClick={() => setMessage('نَتَكَلَّمُ الْإِنْجِلِيزِيَّةَ.')}>Choice 1</button><button type="button" onClick={() => setMessage('أَنَا أَدْرُسُ الْفُصْحَى.')}>Choice 2</button></div><button className="button" type="button" disabled={!message.trim()} onClick={() => { setMessage(''); next(); }}>Next round →</button></section>}
    {stage === 'report' && <section className="speaking-panel speaking-report"><h2>Conversation report</h2><p dir="ltr">Comprehension: {comprehensionCorrect}/5 (minimum 4) · Dialogue building: {built}/{lesson02ConversationPractice.buildDialogue.length} · Role play: completed · Guided conversation: 6 rounds</p>{!completionCriteriaMet && <p className="speaking-wrong" dir="ltr">Review the comprehension or dialogue-building activity. The package requires 4/5 comprehension and a complete dialogue.</p>}<button className="button" type="button" disabled={!completionCriteriaMet || reportViewed} onClick={() => { setReportViewed(true); markLesson2SectionComplete('conversation'); }}>{reportViewed ? 'Report reviewed ✓' : 'Confirm report review'}</button>{reportViewed && <LessonCompletion level="A1" lesson={2} section="conversation" passed markCompleted score={`${percent}% · package completion criteria met`} onRetry={reset} />}</section>}
  </main>;
}

function Question({ title, prompt, options, answer, feedback, onAnswer, onReplay, onNext, nextLabel = 'Next →' }: { title: string; prompt: string; options: readonly string[]; answer: string; feedback: string; onAnswer: (value: string) => void; onReplay?: () => void; onNext: () => void; nextLabel?: string }) { return <section className="speaking-panel speaking-question"><div className="eyebrow">{title}</div><h2>{prompt}</h2><div className="reading-options">{options.map(option => <button type="button" className={answer === option ? 'selected' : ''} key={option} onClick={() => onAnswer(option)}>{option}</button>)}</div>{feedback && <p className={feedback.startsWith('Correct') ? 'speaking-correct' : 'speaking-wrong'}>{feedback}</p>}{onReplay && <button className="review-button" type="button" onClick={onReplay}>🔊 Replay the clue</button>}<button className="button" type="button" disabled={!feedback} onClick={onNext}>{nextLabel}</button></section>; }
