import 'server-only';

// Generated by the attached package build script. Do not edit directly.
export const lessonExam = {
  "exam": {
    "id": "level-02-lesson-01-final-exam",
    "titleAr": "امتحان الدرس الأول",
    "titleEn": "Lesson 1 Final Exam",
    "level": "Lower-intermediate (A2+/B1-)",
    "totalScore": 100,
    "passScore": 80,
    "estimatedMinutes": {
      "minimum": 45,
      "maximum": 55
    },
    "gradedTasks": 20,
    "sections": [
      {
        "id": "vocabulary",
        "titleAr": "المفردات",
        "titleEn": "Vocabulary",
        "score": 20,
        "minutes": 7,
        "items": 5
      },
      {
        "id": "reading",
        "titleAr": "القراءة",
        "titleEn": "Reading",
        "score": 20,
        "minutes": 10,
        "items": 4
      },
      {
        "id": "listening",
        "titleAr": "الاستماع",
        "titleEn": "Listening",
        "score": 20,
        "minutes": 8,
        "items": 4
      },
      {
        "id": "grammar",
        "titleAr": "القواعد",
        "titleEn": "Grammar",
        "score": 20,
        "minutes": 8,
        "items": 5
      },
      {
        "id": "writing",
        "titleAr": "الكتابة",
        "titleEn": "Writing",
        "score": 10,
        "minutes": 12,
        "items": 1,
        "minimumToPass": 5
      },
      {
        "id": "speaking",
        "titleAr": "المحادثة الصوتية",
        "titleEn": "Speaking",
        "score": 10,
        "minutes": 5,
        "items": 1,
        "minimumToPass": 5
      }
    ],
    "progressionRule": "Pass with at least 80/100 and at least 5/10 in both writing and speaking.",
    "attemptPolicy": {
      "maxListeningPlays": 2,
      "autosave": true,
      "showAnswersBeforeSubmit": false,
      "unlimitedRetakes": true,
      "keepBestScore": true,
      "shuffleOptions": true,
      "resumeInterruptedAttempt": true
    }
  },
  "coverage": {
    "vocabularyFamilies": [
      "تعلم",
      "علم",
      "درس",
      "عمل",
      "شارك",
      "خطط",
      "قرر",
      "اختار",
      "استعمل",
      "ساعد",
      "احتاج",
      "تواصل",
      "اهتم",
      "تغير",
      "تطور",
      "نجح"
    ],
    "grammar": [
      "أنْ + المضارع المنصوب",
      "حرف الجر + المصدر"
    ],
    "skills": [
      "recall",
      "understanding",
      "application",
      "reading",
      "listening",
      "writing",
      "speaking"
    ]
  },
  "reading": {
    "titleAr": "خطة مريم لتطوير مهاراتها",
    "wordCount": 147,
    "textAr": "تدرس مريم في معهد للغات، وهي مهتمة بتعلّم العربية من أجل عملها. في بداية الفصل قررت أن تطوّر مهارة الكلام، فخططت للدراسة مدة ثلاثة أشهر. اختارت موضوعًا جديدًا كل أسبوع، واستعملت تطبيقًا لتنظيم وقتها، وشاركت في نادٍ لغوي كل يوم سبت. كما تواصلت مع معلمتها عندما احتاجت إلى شرح كلمة أو قاعدة.\n\nبعد شهر تغيّر جدول عمل مريم، ولم تعد تستطيع الحضور في الصباح. لذلك اختارت أن تدرس في المساء بدلًا من ترك البرنامج. كانت الكتابة أصعب مهارة عندها، فساعدتها زميلتها على فهم الأخطاء وتنظيم الأفكار. وبفضل العمل المستمر، تطور مستواها تدريجيًا.\n\nفي نهاية الأشهر الثلاثة قدمت مريم عرضًا قصيرًا بالعربية أمام زملائها. تكلمت بوضوح وأجابت عن أسئلتهم، فشعرت أن خطتها نجحت. تقول مريم إن النجاح لا يحتاج إلى وقت طويل فقط، بل يحتاج أيضًا إلى تخطيط وتواصل ومشاركة. وتنصح كل متعلم بأن يختار هدفًا واضحًا، وأن يغير خطته إذا تغيرت ظروفه، من غير أن يترك التعلم.",
    "releasePolicy": "Visible only during reading; no translation or dictionary overlay in exam mode."
  },
  "listening": {
    "titleAr": "مراحل مشروع دراسي",
    "audio": "audio/exam-listening-full.mp3",
    "source": "New exam master assembled from six clean studio sentence masters from Lesson 1 vocabulary; it does not reuse the lesson listening recording.",
    "speaker": "Arabic educational narrator",
    "scriptAr": [
      "يَهْتَمُّ يُوسُفُ بِتَارِيخِ المُدُنِ القَدِيمَةِ.",
      "اِخْتَارَ الطَّالِبُ مَوْضُوعًا يُنَاسِبُ اهْتِمَامَهُ.",
      "خَطَّطَ الفَرِيقُ لِإِنْهَاءِ العَمَلِ فِي أُسْبُوعٍ.",
      "اِسْتَعْمَلْنَا تَطْبِيقًا لِتَنْظِيمِ المَوَاعِيدِ.",
      "سَاعَدَنِي زَمِيلِي عَلَى فَهْمِ التَّمْرِينِ.",
      "نَجَحَ الفَرِيقُ فِي تَنْفِيذِ خُطَّتِهِ."
    ],
    "policy": {
      "maxPlays": 2,
      "transcriptVisibleBeforeSubmit": false,
      "allowSeeking": false,
      "playbackSpeed": 1,
      "countPlayAfterPercent": 80
    }
  },
  "writing": {
    "promptAr": "اكتب بين 70 و90 كلمة عن خطة واقعية لتطوير مهارة تريد تعلمها. اذكر هدفك، والمدة، وما ستستعمله، ومن سيساعدك، وكيف ستعرف أنك نجحت. استعمل خمس كلمات من مفردات الدرس، وجملة فيها «أنْ + المضارع»، وتعبيرًا فيه «حرف جر + مصدر».",
    "promptEn": "Write 70–90 Arabic words about a realistic plan to develop a skill you want to learn. State your goal, duration, resources, who will help you, and how you will know you succeeded. Use five Lesson 1 words, one an + present verb structure, and one preposition + verbal noun structure.",
    "wordRange": {
      "minimum": 70,
      "maximum": 90
    },
    "acceptWithoutDiacritics": true,
    "score": 10,
    "rubric": [
      {
        "id": "task",
        "max": 3,
        "labelAr": "إنجاز المهمة"
      },
      {
        "id": "vocabulary",
        "max": 2,
        "labelAr": "مفردات الدرس"
      },
      {
        "id": "grammar",
        "max": 2,
        "labelAr": "القاعدتان"
      },
      {
        "id": "organization",
        "max": 2,
        "labelAr": "تنظيم الأفكار"
      },
      {
        "id": "mechanics",
        "max": 1,
        "labelAr": "الإملاء والترقيم"
      }
    ]
  },
  "speaking": {
    "scenarioAr": "تخطط مع المحاور لنادٍ أسبوعي يساعد الطلاب على تطوير العربية. اختر هدفًا، واقترح نشاطين، وقسّم العمل، ثم عالج تغيرًا مفاجئًا في الموعد واتخذ قرارًا نهائيًا.",
    "score": 10,
    "durationMinutes": {
      "minimum": 3,
      "maximum": 5
    },
    "minimumLearnerTurns": 6,
    "minimumVocabularyFamilies": 5,
    "model": "gpt-realtime-2.1",
    "transport": "WebRTC",
    "voice": "marin",
    "rubric": [
      {
        "id": "task",
        "max": 3,
        "labelAr": "إنجاز المهمة"
      },
      {
        "id": "vocabulary",
        "max": 2,
        "labelAr": "تفعيل المفردات"
      },
      {
        "id": "grammar",
        "max": 2,
        "labelAr": "القاعدتان"
      },
      {
        "id": "interaction",
        "max": 2,
        "labelAr": "التفاعل والترابط"
      },
      {
        "id": "intelligibility",
        "max": 1,
        "labelAr": "وضوح الكلام",
        "note": "Do not deduct for a foreign accent if intelligible."
      }
    ]
  }
} as const;

export const examQuestions = {
  "questions": [
    {
      "id": "v01",
      "section": "vocabulary",
      "type": "multiple_choice",
      "points": 4,
      "promptAr": "اختر الجملة التي تستعمل الفعل «اِحْتَاجَ» استعمالًا صحيحًا.",
      "promptEn": "Choose the sentence that uses احتاج correctly.",
      "options": [
        "يحتاج المشروع إلى وقتٍ.",
        "يحتاج المشروع في وقتٍ.",
        "يحتاج المشروع عن وقتٍ.",
        "يحتاج المشروع من وقتٍ."
      ],
      "answer": 0,
      "feedbackAr": "يأتي الفعل «احتاج» غالبًا مع حرف الجر «إلى».",
      "feedbackEn": "The verb احتاج is normally followed by the preposition إلى."
    },
    {
      "id": "v02",
      "section": "vocabulary",
      "type": "multiple_choice",
      "points": 4,
      "promptAr": "ما مصدر الفعل «تَوَاصَلَ»؟",
      "promptEn": "What is the verbal noun of تواصل؟",
      "options": [
        "وصول",
        "اتصال",
        "تواصل",
        "مواصلة"
      ],
      "answer": 2,
      "feedbackAr": "مصدر «تواصل» هو «تواصل».",
      "feedbackEn": "The verbal noun of تواصل is تواصل."
    },
    {
      "id": "v03",
      "section": "vocabulary",
      "type": "multiple_choice",
      "points": 4,
      "promptAr": "الشخص الذي يشارك في النشاط هو…",
      "promptEn": "A person who participates in an activity is…",
      "options": [
        "مُشَارَك",
        "مُشَارِك",
        "مُسْتَعْمِل",
        "مُخَطِّط"
      ],
      "answer": 1,
      "feedbackAr": "اسم الفاعل من «شارك» هو «مشارك».",
      "feedbackEn": "The active participle of شارك is مشارك."
    },
    {
      "id": "v04",
      "section": "vocabulary",
      "type": "multiple_choice",
      "points": 4,
      "promptAr": "اختر الفعل الماضي الذي يعني: to choose.",
      "promptEn": "Choose the past-tense verb meaning “to choose.”",
      "options": [
        "قَرَّرَ",
        "اِخْتَارَ",
        "اِهْتَمَّ",
        "تَغَيَّرَ"
      ],
      "answer": 1,
      "feedbackAr": "«اختار» يعني أخذ واحدًا من بدائل متعددة.",
      "feedbackEn": "اختار means to select one option from several choices."
    },
    {
      "id": "v05",
      "section": "vocabulary",
      "type": "multiple_choice",
      "points": 4,
      "promptAr": "أكمل: بعد التدريب اليومي، ____ مستوى الطالب.",
      "promptEn": "Complete: After daily practice, the student's level ____.",
      "options": [
        "تَوَاصَلَ",
        "اِسْتَعْمَلَ",
        "تَطَوَّرَ",
        "عَلَّمَ"
      ],
      "answer": 2,
      "feedbackAr": "«تطور المستوى» يعني أنه تحسن تدريجيًا.",
      "feedbackEn": "تطور means that the level developed or improved gradually."
    },
    {
      "id": "r01",
      "section": "reading",
      "type": "multiple_choice",
      "points": 5,
      "promptAr": "ما هدف مريم الأساسي في بداية الفصل؟",
      "promptEn": "What was Mariam's main goal at the start of the term?",
      "options": [
        "تغيير عملها",
        "تطوير مهارة الكلام",
        "تعليم زميلتها",
        "السفر إلى مدينة جديدة"
      ],
      "answer": 1,
      "feedbackAr": "قررت مريم أن تطور مهارة الكلام بالعربية.",
      "feedbackEn": "Mariam decided to develop her Arabic speaking skill."
    },
    {
      "id": "r02",
      "section": "reading",
      "type": "multiple_choice",
      "points": 5,
      "promptAr": "ماذا فعلت مريم عندما تغيّر جدول عملها؟",
      "promptEn": "What did Mariam do when her work schedule changed?",
      "options": [
        "تركت البرنامج",
        "غيّرت هدفها",
        "اختارت الدراسة مساءً",
        "توقفت شهرًا"
      ],
      "answer": 2,
      "feedbackAr": "عدّلت الوقت وواصلت البرنامج بدل تركه.",
      "feedbackEn": "She changed her study time to the evening and continued."
    },
    {
      "id": "r03",
      "section": "reading",
      "type": "multiple_choice",
      "points": 5,
      "promptAr": "في أي مهارة احتاجت مريم إلى مساعدة زميلتها؟",
      "promptEn": "Which skill required help from Mariam's colleague?",
      "options": [
        "الاستماع",
        "القراءة",
        "الكلام",
        "الكتابة"
      ],
      "answer": 3,
      "feedbackAr": "كانت الكتابة أصعب مهارة، فساعدتها زميلتها.",
      "feedbackEn": "Writing was her hardest skill, so her colleague helped her."
    },
    {
      "id": "r04",
      "section": "reading",
      "type": "multiple_choice",
      "points": 5,
      "promptAr": "ما الدليل الأقوى على نجاح خطة مريم؟",
      "promptEn": "What is the strongest evidence that Mariam's plan succeeded?",
      "options": [
        "اشترت تطبيقًا",
        "حضرت يوم السبت",
        "قدمت عرضًا وأجابت عن الأسئلة",
        "غيّرت جدولها"
      ],
      "answer": 2,
      "feedbackAr": "العرض الواضح والإجابة عن الأسئلة تطبيق مباشر للمهارة التي تعلمتها.",
      "feedbackEn": "Giving a clear presentation and answering questions directly demonstrated her skill."
    },
    {
      "id": "l01",
      "section": "listening",
      "type": "multiple_choice",
      "points": 5,
      "promptAr": "بماذا يهتم يوسف؟",
      "promptEn": "What is Youssef interested in?",
      "options": [
        "تاريخ المدن القديمة",
        "الرياضة الحديثة",
        "تعليم الأطفال",
        "تنظيم المواعيد"
      ],
      "answer": 0,
      "feedbackAr": "ذكر التسجيل اهتمام يوسف بتاريخ المدن القديمة.",
      "feedbackEn": "The recording says Youssef is interested in the history of ancient cities."
    },
    {
      "id": "l02",
      "section": "listening",
      "type": "multiple_choice",
      "points": 5,
      "promptAr": "لماذا اختار الطالب الموضوع؟",
      "promptEn": "Why did the student choose the topic?",
      "options": [
        "لأنه سهل جدًا",
        "لأنه يناسب اهتمامه",
        "لأن المعلم اختاره",
        "لأنه يحتاج إلى أسبوعين"
      ],
      "answer": 1,
      "feedbackAr": "اختار موضوعًا يناسب اهتمامه.",
      "feedbackEn": "He chose a topic that matched his interest."
    },
    {
      "id": "l03",
      "section": "listening",
      "type": "multiple_choice",
      "points": 5,
      "promptAr": "ماذا استعمل الفريق لتنظيم المواعيد؟",
      "promptEn": "What did the team use to organize appointments?",
      "options": [
        "كتابًا",
        "تطبيقًا",
        "خريطةً",
        "هاتفًا قديمًا"
      ],
      "answer": 1,
      "feedbackAr": "استعمل الفريق تطبيقًا لتنظيم المواعيد.",
      "feedbackEn": "The team used an app to organize appointments."
    },
    {
      "id": "l04",
      "section": "listening",
      "type": "multiple_choice",
      "points": 5,
      "promptAr": "ما نتيجة العمل في نهاية التسجيل؟",
      "promptEn": "What was the result at the end of the recording?",
      "options": [
        "تغيّر الموضوع",
        "توقف الفريق",
        "نجح الفريق في تنفيذ خطته",
        "احتاج الفريق إلى شهر"
      ],
      "answer": 2,
      "feedbackAr": "تنتهي القطعة بنجاح الفريق في تنفيذ خطته.",
      "feedbackEn": "The passage ends with the team successfully carrying out its plan."
    },
    {
      "id": "g01",
      "section": "grammar",
      "type": "multiple_choice",
      "points": 4,
      "promptAr": "أكمل: قررتُ أنْ ____ العربيةَ كلَّ يوم.",
      "promptEn": "Complete with the correct verb form.",
      "options": [
        "أدرسُ",
        "أدرسَ",
        "درستُ",
        "دراسة"
      ],
      "answer": 1,
      "feedbackAr": "بعد «أنْ» يكون المضارع منصوبًا: أدرسَ.",
      "feedbackEn": "After أنْ, the present verb is subjunctive: أدرسَ."
    },
    {
      "id": "g02",
      "section": "grammar",
      "type": "multiple_choice",
      "points": 4,
      "promptAr": "أي جملة تحتوي على «حرف جر + مصدر»؟",
      "promptEn": "Which sentence contains a preposition followed by a verbal noun?",
      "options": [
        "يريد أن يتعلمَ.",
        "نجح في تنظيمِ الوقت.",
        "تغيّر الجدول صباحًا.",
        "المشارك مهتمّ."
      ],
      "answer": 1,
      "feedbackAr": "«في» حرف جر و«تنظيم» مصدر مجرور.",
      "feedbackEn": "في is a preposition and تنظيم is a following verbal noun."
    },
    {
      "id": "g03",
      "section": "grammar",
      "type": "multiple_choice",
      "points": 4,
      "promptAr": "اختر إعادة الصياغة الصحيحة: أريدُ تعلّمَ العربية.",
      "promptEn": "Choose the correct reformulation.",
      "options": [
        "أريدُ أنْ أتعلمَ العربيةَ.",
        "أريدُ أنْ أتعلمُ العربيةَ.",
        "أريدُ في أتعلمَ العربيةَ.",
        "أريدُ أنْ تعلّمتُ العربيةَ."
      ],
      "answer": 0,
      "feedbackAr": "يمكن تحويل المصدر إلى «أنْ + مضارع منصوب»: أن أتعلمَ.",
      "feedbackEn": "The verbal noun can be restated with أنْ + subjunctive: أن أتعلمَ."
    },
    {
      "id": "g04",
      "section": "grammar",
      "type": "multiple_choice",
      "points": 4,
      "promptAr": "أكمل: نحتاجُ إلى ____ جيّدٍ قبل بدء المشروع.",
      "promptEn": "Complete with the correct verbal noun.",
      "options": [
        "نخططُ",
        "خطّطَ",
        "تخطيطٍ",
        "مخطِّطٌ"
      ],
      "answer": 2,
      "feedbackAr": "بعد «إلى» نحتاج اسمًا مجرورًا؛ «تخطيط» مصدر مناسب.",
      "feedbackEn": "After إلى, a genitive noun is needed; تخطيط is the appropriate verbal noun."
    },
    {
      "id": "g05",
      "section": "grammar",
      "type": "multiple_choice",
      "points": 4,
      "promptAr": "اختر الجملة الصحيحة.",
      "promptEn": "Choose the grammatically correct sentence.",
      "options": [
        "ساعدني زميلي على فهمِ التمرين.",
        "ساعدني زميلي على أفهمُ التمرين.",
        "ساعدني زميلي أن فهمِ التمرين.",
        "ساعدني زميلي إلى أفهمَ التمرين."
      ],
      "answer": 0,
      "feedbackAr": "بعد «على» يأتي المصدر المجرور: على فهمِ.",
      "feedbackEn": "After على, use the genitive verbal noun: على فهمِ."
    }
  ]
} as const;
