create table if not exists public.conversation_room_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id text not null,
  started_at timestamptz,
  ended_at timestamptz not null default now(),
  duration_seconds integer not null default 0 check (duration_seconds between 0 and 900),
  completed boolean not null default false,
  score smallint not null default 0 check (score between 0 and 20),
  best_score smallint not null default 0 check (best_score between 0 and 20),
  dimensions jsonb not null default '{}'::jsonb,
  used_expressions jsonb not null default '[]'::jsonb,
  help_count integer not null default 0,
  transcript jsonb,
  created_at timestamptz not null default now()
);

alter table public.conversation_room_attempts enable row level security;

drop policy if exists "Learners can read own conversation attempts" on public.conversation_room_attempts;
create policy "Learners can read own conversation attempts"
on public.conversation_room_attempts for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Learners can insert own conversation attempts" on public.conversation_room_attempts;
create policy "Learners can insert own conversation attempts"
on public.conversation_room_attempts for insert to authenticated
with check (auth.uid() = user_id);

create index if not exists conversation_room_attempts_user_lesson_idx
on public.conversation_room_attempts (user_id, lesson_id, score desc);
